Creating the Azure Blob Storage

diff --git a/.github/workflows/dev-workflow.yml b/.github/workflows/dev-workflow.yml
--- a/.github/workflows/dev-workflow.yml
+++ b/.github/workflows/dev-workflow.yml
@@ -305,110 +305,118 @@ jobs:
           TERRAGRUNT_TFPATH: /usr/local/bin/terraform
         run: terragrunt apply --auto-approve
 
-
-
-
-  # 6. Post-deployment verification
-  verify:
-    name: Verify Buckets Exist
-    # needs: [aws-deploy, azure-deploy]
-    needs: [azure-deploy]
-    runs-on: self-hosted
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-
-      - name: Install system dependencies
+      - name: Read Azure storage name
+        working-directory: azure
+        id: azure_out
+        run: echo "::set-output name=storage::$(terragrunt output -raw storage_account_name)"
+      
+      - name: Verify Azure Storage Account
         run: |
-          sudo apt-get update
-          sudo apt-get install -y unzip curl
+          az storage account show --name ${{ steps.azure_out.outputs.storage }} || { echo "Missing"; exit 1; }
+      
 
-      - name: Setup Terraform
-        id: terraform
-        uses: hashicorp/setup-terraform@v2
-        with:
-          terraform_version: 1.5.7
-      - name: Install Terragrunt & TFLint
-        run: |
-          # Terragrunt (if you also use Terragrunt in other jobs)
-          curl -Lo terragrunt \
-            https://github.com/gruntwork-io/terragrunt/releases/download/v0.54.1/terragrunt-linux-amd64
-          chmod +x terragrunt && sudo mv terragrunt /usr/local/bin/
 
-      - name: Install Azure CLI
-        run: |
-         curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-east-1
+  # # 6. Post-deployment verification
+  # verify:
+  #   name: Verify Buckets Exist
+  #   # needs: [aws-deploy, azure-deploy]
+  #   needs: [azure-deploy]
+  #   runs-on: self-hosted
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+
+  #     - name: Install system dependencies
+  #       run: |
+  #         sudo apt-get update
+  #         sudo apt-get install -y unzip curl
+
+  #     - name: Setup Terraform
+  #       id: terraform
+  #       uses: hashicorp/setup-terraform@v2
+  #       with:
+  #         terraform_version: 1.5.7
+  #     - name: Install Terragrunt & TFLint
+  #       run: |
+  #         # Terragrunt (if you also use Terragrunt in other jobs)
+  #         curl -Lo terragrunt \
+  #           https://github.com/gruntwork-io/terragrunt/releases/download/v0.54.1/terragrunt-linux-amd64
+  #         chmod +x terragrunt && sudo mv terragrunt /usr/local/bin/
+
+  #     - name: Install Azure CLI
+  #       run: |
+  #        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
+  #     - name: Configure AWS credentials
+  #       uses: aws-actions/configure-aws-credentials@v4
+  #       with:
+  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #         aws-region: us-east-1
     
-      # - name: Verify AWS buckets
-      #   run: |
-      #     aws s3 ls | grep infra-auto-terraform || { echo "AWS bucket missing"; exit 1; }
+  #     # - name: Verify AWS buckets
+  #     #   run: |
+  #     #     aws s3 ls | grep infra-auto-terraform || { echo "AWS bucket missing"; exit 1; }
 
 
-      - name: Configure Azure CLI
-        run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+  #     - name: Configure Azure CLI
+  #       run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
 
-      - name: Verify Azure Storage
-        run: |
-          az storage account list --query "[?name=='mystorageacct']" -o table || { echo "Azure storage missing"; exit 1; }
+  #     - name: Verify Azure Storage
+  #       run: |
+  #         az storage account list --query "[?name=='mystorageacct']" -o table || { echo "Azure storage missing"; exit 1; }
 
-  # 7. Rollback on failure
-  rollback:
-    name: Rollback on Failure
-    if: failure()
-    # needs: [aws-deploy, azure-deploy]
-    needs: [verify]
-    runs-on: self-hosted
-    steps:
-      - uses: actions/checkout@v4
+  # # 7. Rollback on failure
+  # rollback:
+  #   name: Rollback on Failure
+  #   if: failure()
+  #   # needs: [aws-deploy, azure-deploy]
+  #   needs: [verify]
+  #   runs-on: self-hosted
+  #   steps:
+  #     - uses: actions/checkout@v4
       
-      - name: Rollback AWS
-        run: |
-          cd aws
-          terragrunt destroy --terragrunt-non-interactive -auto-approve
+  #     - name: Rollback AWS
+  #       run: |
+  #         cd aws
+  #         terragrunt destroy --terragrunt-non-interactive -auto-approve
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: '20'
+  #     - name: Set up Node.js
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version: '20'
 
-      - name: Install Terraform & Terragrunt
-        run: |
-          curl -fsSL https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip -o terraform.zip
-          unzip terraform.zip
-          sudo mv terraform /usr/local/bin/terraform175
-          sudo ln -sf /usr/local/bin/terraform175 /usr/local/bin/terraform
+  #     - name: Install Terraform & Terragrunt
+  #       run: |
+  #         curl -fsSL https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip -o terraform.zip
+  #         unzip terraform.zip
+  #         sudo mv terraform /usr/local/bin/terraform175
+  #         sudo ln -sf /usr/local/bin/terraform175 /usr/local/bin/terraform
 
-          curl -L -o terragrunt https://github.com/gruntwork-io/terragrunt/releases/latest/download/terragrunt_linux_amd64
-          chmod +x terragrunt
-          sudo mv terragrunt /usr/local/bin/
+  #         curl -L -o terragrunt https://github.com/gruntwork-io/terragrunt/releases/latest/download/terragrunt_linux_amd64
+  #         chmod +x terragrunt
+  #         sudo mv terragrunt /usr/local/bin/
       
-          terraform -version
-          terragrunt -version
+  #         terraform -version
+  #         terragrunt -version
 
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-east-1
+  #     - name: Configure AWS credentials
+  #       uses: aws-actions/configure-aws-credentials@v4
+  #       with:
+  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #         aws-region: us-east-1
 
-      # - name: Rollback Azure
-      #   run: |
-      #     cd azure/storage
-      #     terragrunt destroy --terragrunt-non-interactive -auto-approve
+  #     # - name: Rollback Azure
+  #     #   run: |
+  #     #     cd azure/storage
+  #     #     terragrunt destroy --terragrunt-non-interactive -auto-approve
 
-      - name: Confirm Rollback
-        run: |
-          echo "AWS buckets after rollback:"
-          aws s3 ls
-          # echo "Azure storage after rollback:"
-          # az storage account list --query "[].name"
+  #     - name: Confirm Rollback
+  #       run: |
+  #         echo "AWS buckets after rollback:"
+  #         aws s3 ls
+  #         # echo "Azure storage after rollback:"
+  #         # az storage account list --query "[].name"
 
 #   # 8. Monitor Pipeline Execution (Slack Notification)
 #   notify:
